import Head from 'next/head'
import Navbar from '../components/Navbar'
import { Footer } from '../components/Footer'
import  {Titulospaginas} from '../components/Titulospaginas'
import  {Termos} from '../components/Termos'
import { Container } from 'react-bootstrap'



export default function TermoseCondicoes(): JSX.Element {
    return (
        <section>
            <Head>
                <title>Voit</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section>
                <Navbar />
            </section>
            <Container>
            <section>
                <Titulospaginas />
            </section>
            <section>
                <Termos />
            </section>
            </Container>
            <section>
                <Footer />
            </section>
        </section>

    )
}
    