import Head from 'next/head'
import Navbar from '../components/Navbar';


export default function Home() {
  return (
    <section>
      <Head>
        <title>Voit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Navbar />
      </section>
    </section>
  )
}
